from sqlalchemy import Column, String, Integer, BigInteger, ForeignKey, DateTime, Date
from sqlalchemy.orm import relationship, declarative_base
from backend.database import engine


Base = declarative_base()


class Status(Base):
    __tablename__ = "status"

    status_id = Column(Integer, primary_key=True)
    status = Column(String)
    color = Column(String)


class User(Base):
    __tablename__ = "users"

    user_id = Column(Integer, primary_key=True)
    user_name = Column(String)
    user_surname = Column(String)
    login = Column(String)
    password = Column(String)  # always a bcrypt hash - see backend/auth.py


class Document(Base):
    __tablename__ = "documents"

    # SQLite has no native UUID type - stored as TEXT, generated with
    # str(uuid.uuid4()) in Python before every insert (see repository.py
    # and main.py). Unlike Postgres, there's no server-side default to
    # fall back on.
    document_id = Column(String(36), primary_key=True)
    status_id = Column(Integer, ForeignKey("status.status_id"))

    doc_name = Column(String)
    extension_ = Column(String)
    absolute_path = Column(String)
    relative_path = Column(String)
    size_ = Column(BigInteger)
    # NOTE: despite the name, this stores a full timestamp
    # ('YYYY-MM-DD HH:MM:SS' from document.created in synchronizer/document.py),
    # not a bare date. Under Postgres this worked anyway because Postgres
    # implicitly casts a timestamp string to DATE on insert; SQLite does no
    # such casting, so the column type has to actually match the data.
    data_utworzenia_dokumentu = Column(DateTime)
    data_zmiany_dokumentu = Column(DateTime)
    hash = Column(String)
    source_ = Column(String)
    rola_osoby_odpowiedzialnej = Column(String)
    zatwierdzone = Column(Integer)  # 0 = not approved, 1 = approved
    user_id = Column(Integer, ForeignKey("users.user_id"))
    data_waznosci = Column(Date)
    start_dt = Column(DateTime)
    end_dt = Column(DateTime)
    data_modyfikacji_statusu_dokumentu = Column(DateTime)

    status = relationship("Status")
    user = relationship("User")


class DocumentVersion(Base):
    __tablename__ = "document_versions"

    # Generated by the SQL trigger itself (lower(hex(randomblob(16)))) -
    # not a real RFC4122 UUID, but unique, which is all that's needed here.
    version_id = Column(String(36), primary_key=True)
    document_id = Column(String(36), ForeignKey("documents.document_id"))
    status_id = Column(Integer, ForeignKey("status.status_id"))

    rola_osoby_odpowiedzialnej = Column(String)
    zatwierdzone = Column(Integer)
    user_id = Column(Integer, ForeignKey("users.user_id"))
    data_waznosci = Column(Date)
    start_dt = Column(DateTime)
    end_dt = Column(DateTime)

    status = relationship("Status")
    user = relationship("User")


class NotApplicableMarker(Base):
    __tablename__ = "not_applicable_markers"

    marker_id = Column(String(36), primary_key=True)
    project_id = Column(String)
    folder = Column(String)  # '' for shared/project-level boxes, never NULL
    stage_name = Column(String)
    user_id = Column(Integer, ForeignKey("users.user_id"))
    created_at = Column(DateTime)

    user = relationship("User")